# Generated by Django 4.2.24 on 2025-09-26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import expenses.models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_accountuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'cycle_start_date',
                    models.DateField(
                        default=expenses.models.default_cycle_start,
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='settings',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
