# Generated by Copilot to seed default expense categories.
from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model('expenses', 'Category')
    default_names = [
        'Housing',
        'Utilities',
        'Groceries',
        'Dining Out',
        'Transportation',
        'Subscriptions',
        'Healthcare',
        'Insurance',
        'Savings & Investments',
        'Entertainment',
    ]
    for name in default_names:
        Category.objects.get_or_create(name=name)


def noop_reverse(apps, schema_editor):
    """Keep custom categories intact on migration rollback."""


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_usersettings'),
    ]

    operations = [
        migrations.RunPython(seed_categories, noop_reverse),
    ]
