# Generated by GitHub Copilot on 2025-09-26
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_seed_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default='Transaction', max_length=120),
            preserve_default=False,
        ),
    ]
