# Generated by Django 4.2.24 on 2025-09-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_transaction_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="currency_code",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar ($)"),
                    ("GBP", "British Pound (£)"),
                    ("EUR", "Euro (€)"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
