# Generated by Django 4.2.24 on 2025-09-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0006_usersettings_currency_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount_in_cents",
            field=models.PositiveBigIntegerField(),
        ),
    ]
